### ISSUE TITLE
Fix the broken model download links

### ISSUE THREAD

**Issue by rejon** [newpalmyra/newpalmyra.org#69] opened 2017-01-09 21:32 UTC
Oops, my bad. I had to nuke our gandi0 server because gandi shutdown hosting and accidentally deleted some download links. What links need to be fixed? How to fix.

Good news, @barrythrew has the models :)

The reason we need some server power is to package the downloads on demand, unless there is a better way to do with github now and/or on gitlab or others community free hosting.

Not bad to find way to do on free hosting, but not a blocker either.

What to do?

**Comment by christopheradams** [comment] 2017-02-06 06:08
You can find the broken links by [searching for gandi0].

[gandi0]: https://github.com/newpalmyra/newpalmyra.org/search?utf8=%E2%9C%93&q=gandi0

Which files were included in the zip to download? Related issue #63

**Comment by christopheradams** [comment] 2017-04-11 10:27
- [ ] identify all broken model links, and document which repos they belong to
- [ ] create a GitHub release for the project, and check if the release contains actual 3d models or not (3D data is stored in Git LFS. Ping @barrythrew if there is a problem accessing this data)
- [ ] if not, create a full ZIP download for each model/repo, and and create a release, this time adding the ZIP file as a binary download for the release
- [ ] update the broken download link to point at the release download

I recommend trying the above steps with one model first and confirming that they work. I don't know if the releases are going to run up against any storage issues on the account.

**Comment by rejon** [comment] 2017-04-11 14:38
looks goos

**Comment by rejon** [comment] 2017-04-11 14:38
good

**Comment by rejon** [comment] 2017-04-11 14:40
If above fails then could setup barrys ziprepomaker script again which handles gitlfs properly. @mlinksva @barrythrew had to workaround github lack of pulling gitlfs files into packages fyi

**Comment by christopheradams** [comment] 2017-04-11 22:19
>  github lack of pulling gitlfs files into packages

You mean releases? So it sounds like creating a release is not enough.

**Comment by christopheradams** [comment] 2017-04-12 00:16
Broken links are to:

* arch-of-triumph.zip
* temple-of-bel.zip
* roman-theater.zip
* temple-of-baalshamin.zip

**Comment by christopheradams** [comment] 2017-04-12 00:30
Confirmed, creating a release does not pull down the git-lfs files.

**Comment by rejon** [comment] 2017-04-12 01:40
A good one to hear from @mlinksva on. If nothing else then quick fix is to redeploy @barrythrew solution cheapest scalable way.

**Comment by christopheradams** [comment] 2017-04-12 01:54
@rejon @barrythrew What was in the original ZIP downloads. The full repository with the models, or just the models?

**Comment by christopheradams** [comment] 2017-04-12 02:00
I'm guessing all the files...

**Comment by mlinksva** [comment] 2017-04-12 02:03
The only way to add git-lfs tracked files to releases is the same as any file that isn't in regular git repo (such as binaries), manually with [releases UI](https://help.github.com/articles/creating-releases/) or with tool ([ex](https://github.com/aktau/github-release#how-to-use)) that uses releases API.

**Comment by christopheradams** [comment] 2017-04-12 02:12
Would it make sense to only upload the models as attachments for the release, since the regular release ZIP will have the rest of the files? This is what a release would look like with the models only as a separate download:

https://github.com/newpalmyra/arch-of-triumph/releases/tag/v1.0

What do you think?

**Comment by christopheradams** [comment] 2017-04-12 02:17
Here's a release with the entire repo (but without the `.git` directory) uploaded as a release attachment:

https://github.com/newpalmyra/temple-of-baalshamin/releases/tag/v1.0

**Comment by mlinksva** [comment] 2017-04-12 02:31
@christopheradams I don't know which makes most sense, as I don't really know how to use the files. 😳 I filed #70 sort of about that. But since all of the files not in LFS are (I assume) small, I guess it's most convenient to include everything in one release attachment.

**Comment by rejon** [comment] 2017-04-12 02:42
Yeah better to include all imo and we should lead on file format documentation as pointed out in #70

**Comment by christopheradams** [comment] 2017-04-12 04:38
Fixed in 5bed29b

**Closed by christopheradams** 2017-04-12 04:38 UTC
Labels: bug, help wanted
